# Generated by Django 4.2.7 on 2023-11-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("image_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("x", models.FloatField()),
                ("y", models.FloatField()),
            ],
        ),
    ]
